apiVersion: v1
kind: Service
metadata:
  name: fast-food-totem-svc
  labels:
    app: fast-food-totem
spec:
  type: LoadBalancer
  selector:
    app: fast-food-totem-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP