apiVersion: v1
kind: Service
metadata:
 name: fast-food-totem
 annotations:
   service.beta.kubernetes.io/aws-load-balancer-name: fast-food-totem
spec:
 type: LoadBalancer
 loadBalancerClass: service.k8s.aws/nlb
 ports:
 — name: web
 protocol: TCP
 port: 80
 targetPort: web  
 selector:
    app: fast-food-totem   