apiVersion: v1
kind: Service
metadata:
  name: fast-food-totem
  labels:
    app: fast-food-totem
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: fast-food-totem-api